apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-customredis
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-customredis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: blog-customredis
    spec:
      nodeSelector:
        workload: api
      containers:
        - name: blog-customredis
          image: acrblogbrxstngprod.azurecr.io/blog-customredis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
