### Login as admin
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}

###
# Login as user
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "userpass"
}
