apiVersion: v2
name: blog-dependencies
description: Tracks Helm chart versions for Dependabot
type: application
version: 0.1.0

dependencies:
  - name: ingress-nginx
    version: 4.15.1
    repository: "https://kubernetes.github.io/ingress-nginx"

  - name: cert-manager
    version: "1.14.5"
    repository: "https://charts.jetstack.io"
