/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rubikscube/scene.gltf -S -T -t -i --resolution=512 --format=webp --output=src/models/RubiksCube.tsx --keepnames 
Files: public/models/rubikscube/scene.gltf [90.15KB] > /home/burke/repos/blog/ui/src/models/scene-transformed.glb [57.72KB] (36%)
Author: SonnyG1 (https://sketchfab.com/SonnyG1)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/standard-mirror-rubiks-cube-silver-7d3e55b0dbc84a50bc6449f05a1f34e3
Title: Standard Mirror Rubik's Cube (Silver)
*/

"use no memo";

import { Mesh, MeshStandardMaterial, AnimationAction, Group } from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { 
  FrustumCullingManager, 
  AssetDisposalManager,
  performanceMonitor 
} from '../engine';
import { useSafeMaterials } from '../hooks/useSafeMaterials';

type GLTFResult = GLTF & {
  nodes: {
    Mirror_Cube_Base_0: Mesh
    ['Piece001_Sticker_SPC-SM_0']: Mesh
  }
  materials: {
    Base: MeshStandardMaterial
    ['Sticker_SPC-SM']: MeshStandardMaterial
  }
  animations: AnimationAction[]
}

interface RubiksCubeProps extends React.ComponentProps<'group'> {
  cullingManager?: FrustumCullingManager;
  assetDisposalManager?: AssetDisposalManager;
  enableOptimizations?: boolean;
}

export function Model({ 
  cullingManager, 
  assetDisposalManager, 
  enableOptimizations = true,
  ...props 
}: RubiksCubeProps) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb') as unknown as GLTFResult
  const groupRef = useRef<Group>(null);
  
  // Create safe materials that handle undefined textures
  const safeMaterials = useSafeMaterials(materials);

  // Optimization setup
  useEffect(() => {
    if (enableOptimizations && cullingManager && groupRef.current) {
      // Register with culling manager
      cullingManager.addObject(groupRef.current, 'rubikscube-model-' + Date.now());
      
      // Register with asset disposal manager
      if (assetDisposalManager) {
        groupRef.current.traverse((child) => {
          if (child instanceof Mesh) {
            if (child.geometry) {
              assetDisposalManager.registerAsset(
                `rubikscube-geometry-${child.name || child.uuid}`,
                child.geometry,
                'medium'
              );
            }
            if (child.material) {
              const materials = Array.isArray(child.material) ? child.material : [child.material];
              materials.forEach((material, index) => {
                assetDisposalManager.registerAsset(
                  `rubikscube-material-${child.name || child.uuid}-${index}`,
                  material,
                  'medium'
                );
              });
            }
          }
        });
      }
      
      // Touch assets for usage tracking
      performanceMonitor.logStats('RubiksCube-Model');
    }
  }, [cullingManager, assetDisposalManager, enableOptimizations]);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh 
        name="Mirror_Cube_Base_0" 
        geometry={nodes.Mirror_Cube_Base_0.geometry} 
        material={safeMaterials.Base} 
        rotation={[-Math.PI / 2, 0, 0]} 
      />
      <mesh 
        name="Piece001_Sticker_SPC-SM_0" 
        geometry={nodes['Piece001_Sticker_SPC-SM_0'].geometry} 
        material={safeMaterials['Sticker_SPC-SM']} 
        rotation={[-Math.PI / 2, 0, 0]} 
      />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
