/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sphere/scene.gltf -S -T -t -i --resolution=512 --format=webp --output=src/models/Sphere.tsx --keepnames 
Files: public/models/sphere/scene.gltf [4.24KB] > /home/burke/repos/blog/ui/src/models/scene-transformed.glb [291.02KB] (-6764%)
Author: Renan (https://sketchfab.com/renandesign3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sphere-albedo-0a74c53cac874c57b41fe31924db7f73
Title: Sphere Albedo
*/

"use no memo";

import { Mesh, MeshStandardMaterial, AnimationAction, Group } from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { 
  FrustumCullingManager, 
  AssetDisposalManager,
  performanceMonitor 
} from '../engine';
import { useSafeMaterials } from '../hooks/useSafeMaterials';

type GLTFResult = GLTF & {
  nodes: {
    Object_2: Mesh
  }
  materials: {
    Sphere: MeshStandardMaterial
  }
  animations: AnimationAction[]
}

interface SphereProps extends React.ComponentProps<'group'> {
  cullingManager?: FrustumCullingManager;
  assetDisposalManager?: AssetDisposalManager;
  enableOptimizations?: boolean;
}

export function Model({ 
  cullingManager, 
  assetDisposalManager, 
  enableOptimizations = true,
  ...props 
}: SphereProps) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb') as unknown as GLTFResult
  const groupRef = useRef<Group>(null);
  
  // Create safe materials that handle undefined textures
  const safeMaterials = useSafeMaterials(materials);

  // Optimization setup
  useEffect(() => {
    if (enableOptimizations && cullingManager && groupRef.current) {
      // Register with culling manager
      cullingManager.addObject(groupRef.current, 'sphere-model-' + Date.now());
      
      // Register with asset disposal manager
      if (assetDisposalManager) {
        groupRef.current.traverse((child) => {
          if (child instanceof Mesh) {
            if (child.geometry) {
              assetDisposalManager.registerAsset(
                `sphere-geometry-${child.name || child.uuid}`,
                child.geometry,
                'medium'
              );
            }
            if (child.material) {
              const materials = Array.isArray(child.material) ? child.material : [child.material];
              materials.forEach((material, index) => {
                assetDisposalManager.registerAsset(
                  `sphere-material-${child.name || child.uuid}-${index}`,
                  material,
                  'medium'
                );
              });
            }
          }
        });
      }
      
      // Touch assets for usage tracking
      performanceMonitor.logStats('Sphere-Model');
    }
  }, [cullingManager, assetDisposalManager, enableOptimizations]);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh 
        name="Object_2" 
        geometry={nodes.Object_2.geometry} 
        material={safeMaterials.Sphere} 
        rotation={[-Math.PI / 2, 0, 0]} 
      />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
